apiVersion: apps/v1
kind: Deployment
metadata: 
    name: subject
    labels:
        app: learn-english
        tier: frontend
spec:
    replicas: 3
    template:
        metadata:
            name: subject
            labels:
                svc: subject-service
        spec:
            hostname: subject
            containers:
                - name: subject
                  image: vikrambindal/learn-english-microservice:subject-service
                  env:
                    - name: DISCOVERY_HOST
                      value: "discovery-server"
                    - name: CONFIG_SERVER_PORT
                      value: "30001"
                    - name: CONFIG_SERVER_HOST
                      value: "config-server"
                    - name: SERVER_PORT
                      value: "9023"
    selector:
        matchLabels:
            svc: subject-service