apiVersion: v1
kind: Service
metadata: 
    name: config-server
    labels:
        app: learn-english
        tier: frontend
spec:
    type: NodePort
    ports:
        - targetPort: 30001
          port: 30001
          nodePort: 30001
    selector:
        svc: config-server