apiVersion: v1
kind: Service
metadata: 
    name: discovery-server
    labels:
        app: learn-english
        tier: frontend
spec:
    type: NodePort
    ports:
        - targetPort: 8761
          port: 8761
          nodePort: 30000
    selector:
        svc: service-discovery