apiVersion: v1
kind: Service
metadata: 
    name: sentence
    labels:
        app: learn-english
        tier: frontend
spec:
    type: NodePort
    ports:
      - targetPort: 9025
        port: 9025
        nodePort: 30010
    selector:
        svc: sentence-service