apiVersion: v1
kind: Service
metadata: 
    name: subject
    labels:
        app: learn-english
        tier: frontend
spec:
    type: NodePort
    ports:
      - targetPort: 9023
        port: 9023
        nodePort: 30006
    selector:
        svc: subject-service